eureka:
  client:
    fetch-registry: true
    
    register-with-eureka: true
    
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
  instance:
    hostname: localhost   
    
    
    
microservice:
  payment-service:
    end-points:
      end-point:
        uri:  http://PAYMENT-SERVICE/Payment/doPayment
  order-service:
    end-points:
      end-point:
        uri:  http://ORDER-SERVICE/order/saveOrder    
